default:
	cd ostests; make

clean:
	cd ostests; make clean

run:
	cd ../../bin; dlxsim -x os.dlx.obj -a -D CDdjY -u ostests.dlx.obj; ee469_fixterminal
	#cd ../../bin; dlxsim -x os.dlx.obj -a -D DCdY -u ostests.dlx.obj; ee469_fixterminal
	#cd ../../bin; dlxsim -x os.dlx.obj -a -D CDdjY -u ostests.dlx.obj; ee469_fixterminal
